project_id = "xnrckjigfltaaanzfzml"

[functions.send-transport-confirmation]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = true

[functions.check-kpi-alerts]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.create-demo-user]
verify_jwt = true
